### ISSUE TITLE
trim() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by Shold** [lysenkobv/Yii-ipgeobase#1]
Warning: trim() expects parameter 1 to be string, array given in projectPath/protected/extensions/ipgeobase/Ipgeobase.php on line 70

`$ips[] = trim(explode($_SERVER['HTTP_X_FORWARDED_FOR'], ', ', 1));`
must be
`$ips[] = trim(explode(', ', $_SERVER['HTTP_X_FORWARDED_FOR'], 1)[0]);`
but it will work only for php >=5.4. For php <5.4 you must take `explode` first! Then you can take first element

**Comment by lysenkobv** [comment]
Hi, Shold.
Thank you for contribution.

___

> must be
> $ips[] = trim(explode(', ', $_SERVER['HTTP_X_FORWARDED_FOR'], 1)[0]);

You right about `explode()` parameters placement. 
Another error that can be caused is that returned value of `explode()` can be an empty string or even `false`.

____

Check out this code below.
Can you test this and create pull request is everything ok?
```php
if (isset($_SERVER['HTTP_X_FORWARDED_FOR']) && is_string($_SERVER['HTTP_X_FORWARDED_FOR'])) {
	$forwarded = $_SERVER['HTTP_X_FORWARDED_FOR'];
	$forwardedArray = preg_split("~\s*,\s*~", $forwarded, -1, PREG_SPLIT_NO_EMPTY);
	if (count($forwardedArray) > 0) {
		$forwardedIp = $forwardedArray[count($forwardedArray) - 1];
		if (inet_pton($forwardedIp) !== false) {
			$ips[] = $forwardedIp;
		}
	}
}
```

**Comment by Shold** [comment]
I mean
```php
$somevar = explode(', ', $_SERVER['HTTP_X_FORWARDED_FOR'], 1); // Return array
$ips[] = trim($somevar[0]); // First element always exists! Because delimiter is not empty
```
It's for PHP < 5.4
